language: php
php:
  - 5.6
  - hhvm
  - nightly

install:
  - composer install
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm -v
  - npm install -g gulp
  - npm install
  
cache:
  directories:
    - node_modules
    - vendor 
  
before_script:
  - composer self-update
  
script:
  - gulp phpUnit
